server: 
  port: ${APPLICATION_PORT:8080} 
  servlet: 
    context-path: /api/v1
    
spring:
  application:
    name: helpdesk
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
  show-actuator: true
    
helpdesk:
  attachments-folder: ${env.ATTACHMENTS_FOLDER}
  
jwt:
  secret: ${env.JWT_SECRET:my-secret-key}

