server: 
  port: 8000 
  servlet: 
    context-path: /api/v1

spring:
  application:
    name: helpdesk
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: postgres
    password: password

helpdesk:
  attachments-folder: /Users/macpro/Documents/helpdeskdoc/

jwt:
  secret: h9G+QWz3G7u0RK5+Q3YzN9Kz+zN5R3F5zYQw3zN6Qk5yW3L0==


# url: ${env.DATABASE_URL}
# username: ${env.DATABASE_USERNAME}
# password: ${env.DATABASE_PASSWORD}
# attachments-folder: ${env.ATTACHMENTS_FOLDER}

